name: Deploy Frontend to EC2

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            git config --global --add safe.directory /home/ec2-user/openagri
            cd /home/ec2-user/openagri
            git fetch origin
            git reset --hard origin/staging
            sudo rm -rf /usr/share/nginx/html/openagri/*
            sudo cp -r frontend/* /usr/share/nginx/html/openagri/
            sudo systemctl reload nginx